### ISSUE TITLE
Support implicit ftp over tls

### ISSUE THREAD

**Issue by roman-1983** [Nicolab/php-ftp-client#12]
Looks like the library doenst support a implicit ftp connection over TLS. :(

**Comment by Nicolab** [comment]
The library support FTP and SSL-FTP (via `ftp_connect()` and `ftp_ssl_connect()`).

Passing `true` to the second argument, It connect to a server FTP via SSL:

```
$ftp = new \FtpClient\FtpClient();
$ftp->connect($host, true);
$ftp->login($login, $password);
```

**Comment by laurent22** [comment]
@roman-1983 is right that the library doesn't support *implicit* FTP over TLS (it only supports explicit). Implicit over TLS has been deprecated though so it shouldn't be used.

**Comment by Nicolab** [comment]
?
No, this library doesn't use FTP over TLS. It's SSL with [ftp_ssl_connect()](http://php.net/manual/en/function.ftp-ssl-connect.php) that is not deprecated.

**Comment by laurent22** [comment]
I mean normally there's two SSL modes: implicit or explicit. As the PHP doc says `ftp_ssl_connect()` only does an *explicit* connection. To support an *implicit* one, the lib would need to use curl and do something like this: https://gist.github.com/maxrice/4544344
