### ISSUE TITLE
[FEATURE] pathExists($path), fileExists($path), dirExists($path), linkExists($path)

### ISSUE THREAD

**Issue by gesior** [Nicolab/php-ftp-client#13]
I know that you can get it from 'list',
but it would be much easier to use, if you add these functions.

Other useful feature would be also cache for these functions (so you can use them a lot on one directory without 1000 'list' command calls in underlying code):

**pathExists($path, $cache = false)** // check for any type
**fileExists($path, $cache = false)**
**dirExists($path, $cache = false)**
**linkExists($path, $cache = false)**

I can make Pull Request, if you got no time to create it.

**Comment by Nicolab** [comment]
Hello,

thanks but I do not have time for this lib (I left the PHP). FtpClient works, it is enough for me.

To add a functionality it is better to extend for creating [your own class](https://github.com/Nicolab/php-ftp-client#extend).
For `dirExists()` you can use `FtpClient->isDir()`.
