### ISSUE TITLE
What about GET?

### ISSUE THREAD

**Issue by lucrus73** [Nicolab/php-ftp-client#15]
How do I use this library to GET a file from a server?

**Comment by ctepeo** [comment]
> See the source code for more details. It is fully documented 📘 

`@method bool fget() fget(resource $handle, string $remote_file, int $mode, int $resumepos = 0) Downloads a file from the FTP server and saves to an open file`

`@method bool get() get(string $local_file, string $remote_file, int $mode, int $resumepos = 0) Downloads a file from the FTP server`

`@method int nb_fget() nb_fget(resource $handle, string $remote_file, int $mode, int $resumepos = 0) Retrieves a file from the FTP server and writes it to an open file (non-blocking)`

`@method int nb_get() nb_get(string $local_file, string $remote_file, int $mode, int $resumepos = 0) Retrieves a file from the FTP server and writes it to a local file (non-blocking)`

**Comment by Nicolab** [comment]
Thanks @ctepeo :)
