### ISSUE TITLE
Unable to connect on Local FileZiller Server

### ISSUE THREAD

**Issue by Luyanda86** [Nicolab/php-ftp-client#16]
Hi

I have posted a question on stackoverflow but seeing that I could not add your library to the tags I felt like opening this issue with you. I have the issue described on the link below: 

http://stackoverflow.com/questions/37346759/fileziller-server-failure-with-php-built-ftp-client 

Please see if you can answer there. Thanking you in advance.

**Comment by ctepeo** [comment]
Hi, I'll duplicate my answer form SO here, so maybe someone will find it useful later

Please, check function definition

`public function connect($host, $ssl = false, $port = 21, $timeout = 90)`

So You need to use something like

`$handler = $this->ns->connect('127.0.0.1',false,54218)->login( '***', '***' );`

**Comment by Luyanda86** [comment]
Thanks for your quick feedback very much appreciated.

**Comment by Nicolab** [comment]
Hello,

may be useful #15 
Thanks @ctepeo.
