### ISSUE TITLE
Add vendor to namespace for next major release

### ISSUE THREAD

**Issue by hollodotme** [Nicolab/php-ftp-client#18]
It would be great if you could add a vendor namespace to this project.

Currently you are using:
```php
<?php

namespace FtpClient;
```

Following best practice and composer standards a better namespace would be:
```php
<?php

namespace Nicolab\FtpClient;
```

As this is a BC break, it should be included in the next major release 2.0.
If I can find the time, I'd like to provide an appropriate PR.

**Comment by Nicolab** [comment]
In user land: 

 * \FtpClient\FtpClient
 * \FtpClient\FtpException

is more friendly than:

 * \Nicolab\FtpClient\FtpClient
 * \Nicolab\FtpClient\FtpException

So, no thanks

**Comment by hollodotme** [comment]
OK. Then I'm sorry to say that you just lost one user land. :(

Btw. if everyone would think so, nobody could have two different libs with the same name in one project. The vendor name is there for a reason.

**Comment by Nicolab** [comment]
It's your choice :)

For the namespace, I prefer the simplicity like:

* https://github.com/Seldaek/monolog (maintainer of composer)
```use \Monolog\ClassName```

* https://github.com/silexphp/Silex (maintained by one of the PSR)
```use \Silex\ClassName```

* https://github.com/laravel/laravel
```use App\ClassName```

* ... and many more PHP projects used extensively.

**Comment by gugglegum** [comment]
I agree with @hollodotme. Usage short namespaces without vendor is a bad tone. It is not modest to select such common namespace. Monolog has the same problem too, but "Monolog" is unique name like brand, whereas "FtpClient" is not. There may be a lot of vendors who may want to use "FtpClient" namespaces for their package and they will conflict each other.
