### ISSUE TITLE
SFTP?

### ISSUE THREAD

**Issue by half2me** [Nicolab/php-ftp-client#20]
Does this work with SFTP?

**Comment by ctepeo** [comment]
Yes, it does. From **README.md**:

Connect to a server FTP via SSL (on port 22 or other port) :

```
$ftp = new \FtpClient\FtpClient();
$ftp->connect($host, true, 22);
$ftp->login($login, $password);
```

**Comment by Nicolab** [comment]
Hello,

 * **s**FTP is provided by SSH.
 * FTP**s** is provided by FTP (over SSL).

See the official PHP doc http://php.net/manual/en/function.ftp-ssl-connect.php

FtpClient work with FTP and FTPs, not with SSH.

**Comment by half2me** [comment]
@Nicolab thanks for the quick answer. Would you welcome a pull request adding SFTP support, or is this out of scope for this project?

**Comment by Nicolab** [comment]
Thanks, the [API is not the same](http://php.net/manual/en/function.ssh2-sftp.php).
I think that it should be another class (like \FtpClient\SftpClient) or another package.

PR welcome, if you want ;)
