### ISSUE TITLE
Warning: ftp_pwd(): Transfer complete

### ISSUE THREAD

**Issue by eleftrik** [Nicolab/php-ftp-client#22]
Hi, I've got a small project which makes use of your library, and everything works.
This evening I cloned my repository on another workstation, with basically the same configuration (Mac OS, nginx, PHP 7.0.3 on Virtualbox, etc.), and now I got this errors:

```
Warning: ftp_pwd(): Transfer complete in /app/public/........../vendor/nicolab/php-ftp-client/src/FtpClient/FtpWrapper.php on line 85

Fatal error: Uncaught FtpClient\FtpException: Unable to resolve the current directory in /app/public/........../vendor/nicolab/php-ftp-client/src/FtpClient/FtpClient.php on line 473
```

These errors are thrown after reaching this line:

`$ftp->scanDir('/', true);`

Can you please help me?
Thanks a lot

**Comment by Nicolab** [comment]
Hello,

`scanDir` use PWD, maybe you are trying to run PWD in a folder where PHP does not have the permission?

Please, check the permissions

**Comment by eleftrik** [comment]
Hi @Nicolab, thanks for your suggestion.
I connect to the same server, with same FTP user / password / ftp mode (passive), so I don't think it's a permission problem.
When running from A, "works on my machine", when running from B I got these warning / error.
A and B have basically the same configuration.
I will check again, thanks for your attention.

**Comment by eleftrik** [comment]
I ran the same code in the host instead of the guest, and It worked.
There's something wrong with the VM (I'm using Local by Flywheel, the VM is a Debian Jessie), but I can't figure out what.

From the command line, in the host, I got 

```
ftp> ls
229 Entering Extended Passive Mode (|||57912|)
150 Opening ASCII mode data connection for file list
<many files>
226 Transfer complete

```

From the command line, in the guest, I got

```
ftp> ls
229 Entering Extended Passive Mode (|||57912|)
150 Opening ASCII mode data connection for file list
<many files>
netin: Connection reset by peer
226 Transfer complete
```

I know this isn't a code related problem, but have you any suggestion? Thank you

**Comment by eleftrik** [comment]
@Nicolab, sorry for bothering you, it was definitely a VM related problem. Upgrading VirtualBox and Vagrant solved this strange ftp issue. Thanks for your time

**Comment by Nicolab** [comment]
No worry, I was at the weekend (without PC) :)
Without explicit log, difficult to see the real problem. Delighted that you have resolved your bug.
