### ISSUE TITLE
Download all files

### ISSUE THREAD

**Issue by candidoalbertosilva** [Nicolab/php-ftp-client#24]
Whats the download server ftp to client ?

**Comment by Nicolab** [comment]
I'm not sure to understand the meaning of the question?

Downloading files via FTP?

**Comment by candidoalbertosilva** [comment]
Sorrry, my english is crap.

Yes! . How to Downloading files via FTP?

**Comment by Nicolab** [comment]
No problem.

The best would be with rsync but via FTP you can download all files with a code like this (not tested).

```php
$remoteBasePath = '/base/path';

// get all paths
$files = $ftp->nlist($remoteBasePath, true);

foreach ($files as $file) {
  // write remote file in the current local directory
  if (!$ftp->get(str_replace($remoteBasePath, '.' . $file, $file), $file)) {
    throw new \Exception('Unable to download the file: ' . $file);
  }
}
```
