### ISSUE TITLE
Not deleting files

### ISSUE THREAD

**Issue by janka99** [Nicolab/php-ftp-client#25]
Hi!
First I gotta tell you, this lib is awesome...

But, there is a problem (at least for me), rmdir() is not working properly.
Thing is, it can remove only empty directory even though I set to do it recursively.

Heres's the code:
``` php
       /**
	 * Remove file or folder from server.
	 * @return boolean Returns true on success
	 */
	function RemoveFile() {
		$msg = new \Plasticbrain\FlashMessages\FlashMessages();
		$parent = dirname($this->path) == '/' ? '' : dirname($this->path);
		$page = 'ftp.php?server='.$this->serverId.'&path='.$parent;

		if ($this->isDir($this->path)) {
			$this->rmdir($this->path, true) ? $msg->success('Success - folder!', $page) : $msg->error('Error!');
			
			return true;
		}

		$this->remove($this->path) ? $msg->success('Success - file!', $page) : $msg->error('Error!');

		return true;
	}
```

Notes:
- I extended your lib and this is part of that class
- I'm using PHP 5.6 hosted on Linux

Am I missing something?
Thanks.

**Comment by Nicolab** [comment]
Hello,

 * What class do you extend? (FtpClient or FtpWrapper).
 * You got an error message?
 * Are you sure that the `$this->path` contains the correct path?

I think you should return the result of the functions, rather than systematically returns `true`.

```php
function RemoveFile() {
		$msg = new \Plasticbrain\FlashMessages\FlashMessages();
		$parent = dirname($this->path) == '/' ? '' : dirname($this->path);
		$page = 'ftp.php?server='.$this->serverId.'&path='.$parent;

		if ($this->isDir($this->path)) {
			if ($this->rmdir($this->path, true)) {
                            $msg->success('Success - folder!', $page);
                            return true;
                        }

                       $msg->error('Error!');
			return false;
		}

		if ($this->remove($this->path)) {
                    $msg->success('Success - file!', $page);
                    return true;
                }

               $msg->error('Error!');
		return false;
	}
```

**Comment by janka99** [comment]
I'm extending FtpClient class and yes, `$this->path` contains correct path.
Hm, I followed your example but still nothing..

I get this error:

`
PHP Warning:  ftp_rmdir(): /folder/bin: Directory not empty in FtpWrapper.php on line 85
`

**Comment by Nicolab** [comment]
I can not reproduce, it works for me.

You have overridden other methods like `remove` or `delete` or other?

**Comment by janka99** [comment]
Hm, no, only that function is related to deleting files.
I didn't changed your code at all too.

Any idea?

**Comment by Nicolab** [comment]
No

**Comment by janka99** [comment]
Everything seems to be alright.
I'll send you an email with whole class so that we can discuss about it.

**Comment by Ang3** [comment]
Missing "delete" method in FtpClient @Nicolab ? You put "@" before calling this method in "remove" method and I didn't find it. Do you confirm ?
