### ISSUE TITLE
Fatal error: Class 'FtpClient\FtpWrapper' not found

### ISSUE THREAD

**Issue by golith** [Nicolab/php-ftp-client#26]
Hi, I seem to be having an issue testing this class.
The error thrown is 
Fatal error: Class 'FtpClient\FtpWrapper' not found

Is there something I have not done or is it a setting i have missed?

**Comment by Nicolab** [comment]
May be the initial `\`:
```php
\FtpClient\FtpWrapper
```

**Comment by golith** [comment]
<?php
require_once 'FtpClient.php';

$login = '##@##.com';
$password = '####';
$source_directory = 'test_upload/';
$target_directory = 'incoming/';

$ftp = new FtpClient\FtpClient();
$ftp->connect($host);
$ftp->login($login, $password);
$ftp->putAll($source_directory, $target_directory, FTP_ASCII);
?>
It throws the same error still.

**Comment by golith** [comment]
<?php
require_once 'FtpClient.php';

$login = '##@##.com';
$password = '##';
$source_directory = 'test_upload/';
$target_directory = 'incoming/';

$ftp = new FtpClient\FtpClient();
$ftp->connect($host);
$ftp->login($login, $password);
$ftp->putAll($source_directory, $target_directory, FTP_ASCII);
?>

**Comment by Nicolab** [comment]
> May be the initial `\`:
>```php
>\FtpClient\FtpWrapper
>```

**Comment by golith** [comment]
do you mean when instantiating new\FtpClient\FtpClient();
as removing the first backslash invokes the same error

**Comment by Nicolab** [comment]
Try with the correct namespace: `new \FtpClient\FtpClient();`

**Comment by golith** [comment]
I have added the namespace i think .. also good pickup on the $host .. i need sleep soon.
```
<?php
namespace FtpClient;

$host = 'ftp.#.com';
$login = '#@#.com';
etc ....
```

**Comment by golith** [comment]
when i remove the \ with namespacing present i get a different error

> Fatal error: Class 'FtpClient\FtpClient\FtpClient' not found

i see it has added another level to the namespace addressing method

**Comment by golith** [comment]
would you mind if i re-hash this class so it does not use namespacing?

**Comment by Nicolab** [comment]
> when i remove the \ with namespacing present i get a different error
> Fatal error: Class 'FtpClient\FtpClient\FtpClient' not found
> i see it has added another level to the namespace addressing method
Logic, it's the behavior of PHP http://php.net/manual/en/language.namespaces.php

> would you mind if i re-hash this class so it does not use namespacing?

Do what you want to do with your copy, but doesn't send your PR without namespace. The PR will be rejected.
The [namespacing](http://php.net/manual/en/language.namespaces.php) is a standard way of PHP. It's useful.

You should use this package normaly, not by adding your files in the package.

I close, this issue because it's not related to the package but to PHP namespace.
