### ISSUE TITLE
Windows_NT raw listing not supported

### ISSUE THREAD

**Issue by laurent22** [Nicolab/php-ftp-client#27]
When a server systype is `Windows_NT`, the result of rawlist is in this format:

    10-27-15  03:46PM   <DIR>     somedir
    10-27-15  03:46PM        456  somefile

which currently is not parsed correctly by the lib and so returns an empty array. See also there for a reliable way to parse it: https://secure.php.net/manual/en/function.ftp-rawlist.php#55936

I've started writing a PR but didn't quite finish as there's many places where the code assumes a Unix systype. It should also probably cache the result of the `systype` command so that it's not necessary to run it every time to detect how the list should be parsed.

**Comment by Nicolab** [comment]
Hello,

Thanks but the Windows-specific behaviors are not supported. I keep this lib simple for Unix environment. 
You can extend `FtpClient` for Windows_NT and other customizations.

**Comment by laurent22** [comment]
Why not though? If say, someone builds an FTP client and doesn't know in advance if the server will be Unix or Windows - it will work in one case and silently fails in another. It'd be like building a browser that only supports Apache servers but fails with Nginx. I can see the appeal of keeping things simple but in this case it feels more like a bug.
