### ISSUE TITLE
calling count() is slowing the server

### ISSUE THREAD

**Issue by anujsharma9196** [Nicolab/php-ftp-client#29]
-  [x] Bug

I have added this to get count of directories in current directory
`$response['content']['count']['directories'] = $ftp->count('.', 'directory');`

But presence of this function is making server down and then no other functions/links are working on my website.
Removing this line is working fine without any issue. 

I also tried count function with file, ans link but same issue.

**Comment by Nicolab** [comment]
If there are several thousand files, in this case it is necessary to use another way to count the files. You can override this method if you want.
